# Generated by Django 4.0.5 on 2022-06-10 08:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_userorder_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='userorder',
            name='product_order',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='product.productorder'),
            preserve_default=False,
        ),
    ]
