# Generated by Django 4.0.5 on 2022-06-10 08:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_userorder_product_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userorder',
            name='product_order',
        ),
        migrations.AddField(
            model_name='productorder',
            name='user_order',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='product.userorder'),
            preserve_default=False,
        ),
    ]
